### PR TITLE
Hotfix/fix skip befor limit

### PR DESCRIPTION
**Pull request by k3z**
Hello, 
I find a little bug in QuerySet when you use skip and limit together. Skip must be added in the _cursor_obj before limit or the query produce no results at all and no exception.

Nice tool by the way

### CODE REVIEW

**Comment by bwind** [comment]
Hey Olivier,

Thanks! Did you run the tests though? Travis says it's broken:
https://travis-ci.org/bwind/rethinkengine/jobs/22597102. I think limit()
works fine as long as it's greater than the value passed to skip().

It's been a while since I touched this functionality, so I'm not exactly
sure, but the tests suggest that it works according to spec.

Just out of curiosity, for what projects are you using
RethinkDB/rethinkengine?

Bas

2014-04-09 12:03 GMT+02:00 Olivier notifications@github.com:

**Comment by k3z** [comment]
All tests pass locally. I dont understand why it's broken with travis.

I use this project for a futur online news site.
I know rethinkengine is not production ready, but I like the simplicity and I want to contribute. I add more tests to see if my fix is strong enough.

I have more suggestions to make.
I have found a solution for this problem :
With foo.list.append('bar'), the object become not dirty. With an observer class this can be solved easily, I make another pull request soon.

**Comment by k3z** [comment]
I started the master branch tests instead of hotfix branch tests.
The skip test is now fixed.

**Comment by harobed** [comment]
+1

**Comment by harobed** [comment]
Why this pull request has been closed ? I didn't see it in rethinkengine commit history.

**Pull request closed without merging**
